name: Release

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

permissions:
    contents: write

jobs:
    test:
        strategy:
            matrix:
                os: [macos-latest, ubuntu-latest]
        runs-on: ${{ matrix.os }}
        if: github.repository == 'ttypic/swift-klib-plugin'
        timeout-minutes: 25

        steps:
            - uses: actions/checkout@v4
            - uses: gradle/wrapper-validation-action@v2
            - uses: actions/setup-java@v4
              with:
                  distribution: 'zulu'
                  java-version: '17'
                  check-latest: true

            - name: Run tests
              run: ./gradlew test
